[package]
name = "hack_vm_translator"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enumset = "1.0.12"
substring = "1.4.5"
clap = { version = "4.0.32", features = ["derive"] }